In [1]:
import pandas as pd

# Reading Data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreadth  infectionProb
0   99.619735         1   36          0            1              0
1  100.042145         0   32          1           -1              0
2  101.156263         0   18          0            1              0
3   98.993634         0   35          0            1              0
4  100.720980         1   67          1            0              1

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreadth  infectionProb
2494   98.275149         0   92          1            1              0
2495   99.894597         0    6          0            0              0
2496  100.023411         1   51          1            0              0
2497   98.270612         1   35          1            1              1
2498   99.323187         1   56          0            0              1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2499 non-null   float64
 1   bodyPain       2499 non-null   int64  
 2   age            2499 non-null   int64  
 3   runnyNose      2499 non-null   int64  
 4   diffBreadth    2499 non-null   int64  
 5   infectionProb  2499 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 117.3 KB


In [9]:
df['diffBreadth'].value_counts()

 1    844
 0    842
-1    813
Name: diffBreadth, dtype: int64

In [10]:
df.describe()

fever     bodyPain          age    runnyNose  diffBreadth  \
count  2499.000000  2499.000000  2499.000000  2499.000000  2499.000000   
mean     99.975577     0.502601    50.112045     0.486995     0.012405   
std       1.154301     0.500093    28.616376     0.499931     0.814357   
min      98.002314     0.000000     1.000000     0.000000    -1.000000   
25%      98.985684     0.000000    26.000000     0.000000    -1.000000   
50%      99.955838     1.000000    50.000000     0.000000     0.000000   
75%     100.948567     1.000000    74.000000     1.000000     1.000000   
max     101.999915     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2499.000000  
mean        0.509404  
std         0.500012  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

# Train Test Splitting

In [11]:
import numpy as np

In [15]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

    
    
    
    
    
    

In [16]:
np.random.permutation(7)

array([4, 6, 2, 3, 5, 0, 1])

In [17]:
train,test=data_split(df,.2)

In [18]:
train

fever  bodyPain  age  runnyNose  diffBreadth  infectionProb
461    99.807893         1   38          1            1              1
109   100.766693         0   42          0            1              1
2296  100.591208         1   98          1            0              1
354    98.828630         1   73          1           -1              0
266   100.089116         0   80          0           -1              1
...          ...       ...  ...        ...          ...            ...
1638   99.091432         0   71          1           -1              0
1095   99.371436         0   71          1            0              0
1130   98.754359         1   54          0           -1              1
1294  100.837355         1   56          1            1              1
860   101.361541         1   86          0            1              1

[2000 rows x 6 columns]

In [19]:
test

fever  bodyPain  age  runnyNose  diffBreadth  infectionProb
2319  101.239901         1   27          0            0              0
1865   99.144823         1   79          1            1              1
902    98.209881         0   34          1            0              1
2240   99.345531         1   97          1           -1              1
1285   99.570827         0   74          1            1              0
...          ...       ...  ...        ...          ...            ...
1037   98.679853         1   85          1            0              1
2054  101.965128         0   96          1            1              1
1860  100.510913         1   65          0            1              1
1862   99.923553         1   82          0           -1              1
1151   98.314606         1   49          1           -1              1

[499 rows x 6 columns]

In [30]:
X_train=train[['fever','bodyPain','age','runnyNose','diffBreadth']].to_numpy()

In [31]:
X_train

array([[ 99.80789278,   1.        ,  38.        ,   1.        ,
          1.        ],
       [100.7666933 ,   0.        ,  42.        ,   0.        ,
          1.        ],
       [100.5912085 ,   1.        ,  98.        ,   1.        ,
          0.        ],
       ...,
       [ 98.75435916,   1.        ,  54.        ,   0.        ,
         -1.        ],
       [100.8373554 ,   1.        ,  56.        ,   1.        ,
          1.        ],
       [101.3615406 ,   1.        ,  86.        ,   0.        ,
          1.        ]])

In [32]:
X_test=test[['fever','bodyPain','age','runnyNose','diffBreadth']].to_numpy()

In [34]:
X_test

array([[101.2399005 ,   1.        ,  27.        ,   0.        ,
          0.        ],
       [ 99.14482297,   1.        ,  79.        ,   1.        ,
          1.        ],
       [ 98.20988116,   0.        ,  34.        ,   1.        ,
          0.        ],
       ...,
       [100.5109127 ,   1.        ,  65.        ,   0.        ,
          1.        ],
       [ 99.92355271,   1.        ,  82.        ,   0.        ,
         -1.        ],
       [ 98.31460624,   1.        ,  49.        ,   1.        ,
         -1.        ]])

In [48]:
Y_train=train[['infectionProb']].to_numpy().reshape(2000,)
Y_test=test[['infectionProb']].to_numpy().reshape(499,)


In [49]:
Y_train


array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
clf=LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [64]:
inputFeatures=[100,1,22,-1,1]
infProb=clf.predict_proba([inputFeatures])[0][1]

In [65]:
infProb

0.556507662394857